### ISSUE TITLE
Please help, can't run the code

### ISSUE THREAD

**Issue by coo37** [linuxscout/yarob#26]
**When I run the !make server command on colab , I got these message:** 

echo "run server on http://127.0.0.1:5000/"
run server on http://127.0.0.1:5000/
cd web; python3 yarob_flask.py
Traceback (most recent call last):
  File "/content/yarob/web/yarob_flask.py", line 52, in <module>
    logging.basicConfig(filename=LOGGING_FILE, level=logging.INFO) 
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/content/yarob/web/logs/demo.log'
make: *** [Makefile:65: server] Error 1

**Comment by francogrex** [comment]
cd web
mkdir logs
cd logs
create an empty demo.log file
